"""Initial AEGIS schema

Revision ID: 0fc8e2093986
Revises: 
Create Date: 2026-09-29 01:11:15.278008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc8e2093986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_vehicles_identifier'), ['identifier'], unique=True)

    op.create_table('intersections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intersections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intersections_identifier'), ['identifier'], unique=True)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eta_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('predicted_arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_seconds', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['emergency_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eta_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eta_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_eta_predictions_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eta_predictions_predicted_arrival_time'), ['predicted_arrival_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_eta_predictions_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('green_corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['emergency_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('green_corridors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_green_corridors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_green_corridors_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_green_corridors_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('route_intersections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('distance_from_start', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'intersection_id', name='uq_route_intersection_pair'),
    sa.UniqueConstraint('route_id', 'sequence_order', name='uq_route_intersection_sequence')
    )
    with op.batch_alter_table('route_intersections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_intersections_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_intersections_route_id'), ['route_id'], unique=False)

    op.create_table('signal_priority_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('requested_state', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['emergency_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_priority_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_priority_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_priority_decisions_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_priority_decisions_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('traffic_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_observations_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_observations_timestamp'), ['timestamp'], unique=False)

    op.create_table('traffic_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=16), nullable=False),
    sa.Column('normal_cycle_seconds', sa.Integer(), nullable=False),
    sa.Column('state_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_signals_intersection_id'), ['intersection_id'], unique=True)

    op.create_table('vehicle_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['emergency_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_positions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_positions_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_positions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_positions_timestamp'))

    op.drop_table('vehicle_positions')
    with op.batch_alter_table('traffic_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_signals_intersection_id'))

    op.drop_table('traffic_signals')
    with op.batch_alter_table('traffic_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_observations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_traffic_observations_intersection_id'))

    op.drop_table('traffic_observations')
    with op.batch_alter_table('signal_priority_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_priority_decisions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_signal_priority_decisions_intersection_id'))
        batch_op.drop_index(batch_op.f('ix_signal_priority_decisions_created_at'))

    op.drop_table('signal_priority_decisions')
    with op.batch_alter_table('route_intersections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_intersections_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_intersections_intersection_id'))

    op.drop_table('route_intersections')
    with op.batch_alter_table('green_corridors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_green_corridors_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_green_corridors_route_id'))
        batch_op.drop_index(batch_op.f('ix_green_corridors_created_at'))

    op.drop_table('green_corridors')
    with op.batch_alter_table('eta_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eta_predictions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_eta_predictions_predicted_arrival_time'))
        batch_op.drop_index(batch_op.f('ix_eta_predictions_intersection_id'))
        batch_op.drop_index(batch_op.f('ix_eta_predictions_created_at'))

    op.drop_table('eta_predictions')
    op.drop_table('routes')
    with op.batch_alter_table('intersections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intersections_identifier'))

    op.drop_table('intersections')
    with op.batch_alter_table('emergency_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_vehicles_identifier'))

    op.drop_table('emergency_vehicles')
    # ### end Alembic commands ###
